### ISSUE TITLE
Лицензия использования тайлов 2GIS в Геомиксере 2.0

### ISSUE THREAD

**Issue by petrovnn** [ScanEx/GeoMixerExamples#1]
Здравствуйте!

На геомиксере 2.0 по умолчанию есть слой 2GIS. Но копирайтов 2GIS на карте не замечено. У вас есть какие-то договоренности с 2GIS, разрешающие так делать? Хочу показывать тайлы 2GIS в лифлете с помощью геомиксера 2.0, но смущает этот момент

**Comment by aparshin** [comment]
Добрый день!

Копирайты 2GIS появляются при переключении на подложку `2GIS` (копирайт выглядит как ссылка `© ООО «ДубльГИС»`). В версии 2.0 их можно увидеть в правом нижнем углу карты, в версии 3.0 - если нажать на ссылку "Copyrights" в левом нижнем углу.

**Comment by aparshin** [comment]
Я закрою этот issue, но если будут вопросы - смело открывайте заново или создавайте новый!
